language: perl
dist: trusty
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.26-shrplib"
  - "5.20"
  - "5.18-shrplib"
  - "5.14"
  - "5.8"

install:
  - cpanm ExtUtils::MakeMaker
  - cpanm --with-recommends --verbose --installdeps --notest .
